model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"

sandbox_mode    = "workspace-write"

approval_policy = "on-request"

[projects."/Users/hidemaru/code/pummit"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/FediGONE"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/chris"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/tunnet"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/bridge"]
trust_level = "trusted"

[projects."/Users/hidemaru"]
trust_level = "trusted"

[projects."/Users/hidemaru/dotfiles"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/mdxsnap.nvim"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/zoho-mail-mcp"]
trust_level = "trusted"

[projects."/Users/hidemaru/code/conjunctions"]
trust_level = "trusted"

[mcp_servers.context7]
command = "bun"
args = ["x", "-y", "@upstash/context7-mcp"]

[mcp_servers.fetch]
command = "bun"
args = ["x", "mcp-server-fetch-typescript"]

[mcp_servers.playwright]
command = "bun"
args = ["x", "@playwright/mcp@latest"]

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[features]
web_search_request = true  # モデルがウェブ検索をリクエストできるようにする（推奨）
